
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-19T23:40:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f56d28bab522c15df3a4a8bc9c9a77c5129bf531",
 "version": "1.4.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
